### ISSUE TITLE
Changesets

### ISSUE THREAD

**Issue by qoomon** [samjarrett/cfn-sync#1]
Thanks for this great tool.
It would be awesome, if this cli would use changesets as `aws cloudwatch deploy` does.

**Comment by samjarrett** [comment]
Hey! Thanks for filing an issue. 

I'm curious what using change sets brings that doing an update or create doesn't meet? 

In the context of `aws cloudformation deploy`, unless you're using the `--no-execute-changeset`, it creates the change set and then immediately executes it, so there isn't really an advantage of this approach as far as I can tell.

**Comment by qoomon** [comment]
Hi, it is useful for two reasons
* you will be able to have a manuel step to deploy within your ci cd pipeline. We will review changesets for critical services and then trigger execution of a change set manually.
* you will be able to see last changeset execution and which resources were affected, quite handy for debugging cause you don't have to gather stack events

**Comment by samjarrett** [comment]
Hey @qoomon just letting you know I'm working on this. :)

**Comment by r2690698** [comment]
hey @samjarrett any news on this ?
